name: Test
on:
  push:
  pull_request:
env:
  FORCE_COLOR: 2
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16
          - 14
          - 12
    name: Node.js ${{ matrix.node-version }} Test
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test